export const sampleData = {
  routes: [
    {
      routeId: "R001",
      shipId: "S1",
      vesselType: "container",
      fuelType: "MGO",
      year: 2024,
      ghgIntensity: 91.16,
      fuelConsumptionTons: 120.5,
      distanceKm: 2000,
      totalEmissionsTons: 4.64,
      baselineSet: false,
    },
    {
      routeId: "R002",
      shipId: "S2",
      vesselType: "tanker",
      fuelType: "HFO",
      year: 2024,
      ghgIntensity: 95.5,
      fuelConsumptionTons: 200.0,
      distanceKm: 5000,
      totalEmissionsTons: 9.55,
      baselineSet: false,
    },
    {
      routeId: "R003",
      shipId: "S3",
      vesselType: "bulk",
      fuelType: "LNG",
      year: 2023,
      ghgIntensity: 80.2,
      fuelConsumptionTons: 50.0,
      distanceKm: 1000,
      totalEmissionsTons: 2.01,
      baselineSet: true,
    },
  ],
  cbs: [
    { shipId: "S1", year: 2024, cbBefore: 5.0, applied: 0, cbAfter: 5.0 },
    { shipId: "S2", year: 2024, cbBefore: -2.0, applied: 0, cbAfter: -2.0 },
    { shipId: "S3", year: 2024, cbBefore: 1.5, applied: 0, cbAfter: 1.5 },
  ],
};
